spring:

  datasource:
    url: jdbc:postgresql://localhost/map
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      databaseplatform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true