spring:

  jpa:
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      databaseplatform: org.hibernate.dialect.PostgreSQLDialect

    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 82273722140-aknjfsd7rvbungeuggcg0sfv7e0s349n.apps.googleusercontent.com
            client-secret: VKVEvxSlBhKxrpoEEwQDHBna
            scope:
              - openid
              - email
              - profile
            redirect-uri: https://desired-charging-map.herokuapp.com/login/oauth2/code/google
          facebook:
            client-id: 678929842802656
            client-secret: af5608edcb4b42e9b723e12d3f8e99ba
            scope:
              - email
              - public_profile

  flyway:
    baseline-on-migrate: true

settings:
  host: https://desired-charging-map.herokuapp.com/
  user:
    maxPointsNumber: 2